name: Build and deploy Node.js app to Azure Web App - birlympics-website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Archive production assets
        run: |
          zip -r app.zip \
            .next \
            public \
            server.js \
            package.json \
            next.config.ts

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: birlympics-website
          package: app.zip
